# -*- coding: utf-8 -*-
"""TASK - 3 - (FB Login Page)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KML-m2jse8QgKXTPOigtQC481gm8lT64
"""

"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>Login</title>"
"<link rel="stylesheet" href=""<login.css>"
"<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<center>
<br>
<h3>Log into Facebook</h3>
<div>
    <input type="text" name="username" placeholder="Your name">
      <br/>
	  <br/>
    <input type="password" name="password" placeholder="Password">
<br/><br/>
  <input id="sb" type="submit" value="Log In">
  </br>
  <p>or</p>
  <input id="sb" type="submit" value="Create New Account">
  <p>Forgot Passsword?</p>
  <p>Not Now</p>
  </form>
  </div>
</center>
</body>
</html>